api_platform:
    title: 'Symfony API Platform REST API'
    description: 'A Symfony API to manage a database'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
